server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: VEHICLE-SERVICE
            uri: lb://VEHICLE-SERVICE
            predicates:
              - path=/api/v1/vehicles/**
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - path=/api/v1/users/**
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - path=/api/v1/payments/**
          - id: TICKET-SERVICE
            uri: lb://TICKET-SERVICE
            predicates:
              - path=/api/v1/tickets/**