server:
  port: 8081
spring:
  application:
    name: VEHICLE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_management?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
